sonar.projectKey=elearning-platform_elearning-frontend-spa
sonar.organization=elearning-platform
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,src/mocks/**,src/app/api/generated/**,**/*.spec.ts
sonar.coverage.exclusions=**/*.spec.ts,**/environments/**,**/main.ts,**/polyfills.ts,src/mocks/**,src/app/api/generated/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
