sonar.projectKey=elearning-platform_elearning-frontend-spa
sonar.organization=elearning-platform
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,src/mocks/**,src/app/api/generated/**
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
