import { ChangeDetectionStrategy, Component, OnInit, computed, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

import { TeacherRevenueStore, BundleRevenue } from './teacher-revenue.store';
import { TeacherBundleStore, TeacherBundle } from '../state/teacher-bundle.store';

import { ButtonComponent } from '../../../shared/components/button/button.component';
import { CardComponent } from '../../../shared/components/card/card.component';

interface RevenueRow {
  bundleId: string;
  bundleName: string;
  lessonsCount: number;
  generatedRevenue: number;
}

@Component({
  selector: 'app-balance-page',
  imports: [CommonModule, RouterModule, ButtonComponent, CardComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="p-6 md:p-8 max-w-7xl mx-auto space-y-8">

      <!-- Header -->
      <div class="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white p-6 rounded-3xl border-4 border-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
        <div class="flex items-center space-x-4">
          <div class="w-16 h-16 bg-[#0ABAB5]/20 rounded-2xl border-4 border-black flex items-center justify-center">
            <span class="material-icons text-[#0ABAB5] text-3xl">account_balance_wallet</span>
          </div>
          <div>
            <h1 class="text-3xl font-black text-black tracking-tight">Balance</h1>
            <p class="text-gray-600 font-medium">Revenue generated by each of your bundles</p>
          </div>
        </div>
        <app-button variant="secondary" icon="refresh" (btnClick)="reload()" [disabled]="isLoading()">
          Refresh
        </app-button>
      </div>

      <!-- Total Summary -->
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <app-card class="block">
          <div class="p-6 flex items-center justify-between">
            <div>
              <p class="text-sm font-bold text-gray-500 uppercase tracking-wider">Total Balance</p>
              <p class="text-4xl font-black text-black mt-2">{{ formatCurrency(revenueStore.totalRevenue()) }}</p>
            </div>
            <div class="w-14 h-14 bg-[#0ABAB5]/10 rounded-2xl border-2 border-black flex items-center justify-center">
              <span class="material-icons text-[#0ABAB5] text-3xl">savings</span>
            </div>
          </div>
        </app-card>

        <app-card class="block">
          <div class="p-6 flex items-center justify-between">
            <div>
              <p class="text-sm font-bold text-gray-500 uppercase tracking-wider">Bundles With Revenue</p>
              <p class="text-4xl font-black text-black mt-2">{{ revenueStore.bundleCount() }}</p>
            </div>
            <div class="w-14 h-14 bg-yellow-100 rounded-2xl border-2 border-black flex items-center justify-center">
              <span class="material-icons text-yellow-600 text-3xl">inventory_2</span>
            </div>
          </div>
        </app-card>
      </div>

      <!-- Revenue Per Bundle -->
      <app-card class="block">
        <div class="p-6 border-b-4 border-black bg-gray-50 flex items-center space-x-3">
          <div class="w-10 h-10 bg-gray-100 rounded-xl border-2 border-black flex items-center justify-center">
            <span class="material-icons text-black">paid</span>
          </div>
          <div>
            <h3 class="text-xl font-black text-black">Revenue Per Bundle</h3>
            <p class="text-xs text-gray-500 font-bold">Live data from the Payments service</p>
          </div>
        </div>

        <div class="p-6">
          @if (isLoading()) {
            <div class="flex flex-col items-center justify-center py-12 space-y-3">
              <span class="material-icons animate-spin text-[#0ABAB5] text-4xl">sync</span>
              <p class="text-sm text-gray-500 font-bold">Loading revenue data...</p>
            </div>
          } @else if (revenueStore.error()) {
            <div class="p-6 text-center bg-red-50 text-red-600 font-bold border-2 border-red-500 rounded-2xl">
              <span class="material-icons text-3xl">error_outline</span>
              <p class="text-sm mt-2">{{ revenueStore.error() }}</p>
            </div>
          } @else if (rows().length === 0) {
            <div class="text-center py-8">
              <span class="material-icons text-gray-400 text-5xl">savings</span>
              <h4 class="text-lg font-black text-black mt-2">No Revenue Yet</h4>
              <p class="text-gray-500 font-bold text-sm mt-1">When students buy your bundles, the revenue will show up here.</p>
              <div class="mt-4">
                <app-button variant="primary" icon="add_circle" routerLink="/teacher/bundles/new">Create a Bundle</app-button>
              </div>
            </div>
          } @else {
            <div class="overflow-x-auto">
              <table class="w-full text-left border-collapse min-w-[500px]">
                <thead>
                  <tr class="border-b-4 border-black bg-gray-100">
                    <th class="p-4 font-black text-gray-600 uppercase tracking-wider text-sm" scope="col">Bundle</th>
                    <th class="p-4 font-black text-gray-600 uppercase tracking-wider text-sm text-center" scope="col">Lessons</th>
                    <th class="p-4 font-black text-gray-600 uppercase tracking-wider text-sm text-right" scope="col">Revenue</th>
                  </tr>
                </thead>
                <tbody>
                  @for (row of rows(); track row.bundleId) {
                    <tr class="border-b-2 border-black/10 hover:bg-[#0ABAB5]/5 transition-colors">
                      <td class="p-4">
                        <div class="flex items-center space-x-3">
                          <div class="w-10 h-10 bg-[#FFD700]/20 rounded-xl border-2 border-black flex items-center justify-center">
                            <span class="material-icons text-black text-base">inventory_2</span>
                          </div>
                          <div>
                            <p class="font-bold text-black">{{ row.bundleName }}</p>
                            <p class="text-xs text-gray-500 font-medium">ID: {{ row.bundleId }}</p>
                          </div>
                        </div>
                      </td>
                      <td class="p-4 text-center">
                        <span class="bg-gray-100 border-2 border-black px-3 py-1 rounded-xl font-bold text-sm">
                          {{ row.lessonsCount }}
                        </span>
                      </td>
                      <td class="p-4 text-right">
                        <span class="bg-[#0ABAB5]/10 text-[#0ABAB5] border-2 border-black px-4 py-1.5 rounded-xl font-black text-base shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]">
                          {{ formatCurrency(row.generatedRevenue) }}
                        </span>
                      </td>
                    </tr>
                  }
                </tbody>
                <tfoot>
                  <tr class="bg-gray-50 border-t-4 border-black">
                    <td class="p-4 font-black text-black uppercase tracking-wider text-sm" colspan="2">Total</td>
                    <td class="p-4 text-right font-black text-black">{{ formatCurrency(revenueStore.totalRevenue()) }}</td>
                  </tr>
                </tfoot>
              </table>
            </div>
          }
        </div>
      </app-card>
    </div>
  `
})
export class BalancePageComponent implements OnInit {
  revenueStore = inject(TeacherRevenueStore);
  bundleStore = inject(TeacherBundleStore);

  readonly isLoading = computed(() => this.revenueStore.loading() || this.bundleStore.loading());

  readonly rows = computed<RevenueRow[]>(() => {
    const bundles = this.bundleStore.bundles();
    const byId = new Map<string, TeacherBundle>(bundles.map((b) => [b.id, b]));

    return this.revenueStore
      .revenues()
      .map((r: BundleRevenue) => {
        const bundle = byId.get(r.bundleId);
        return {
          bundleId: r.bundleId,
          bundleName: bundle?.name ?? 'Unknown bundle',
          lessonsCount: bundle?.lessons.length ?? 0,
          generatedRevenue: r.generatedRevenue,
        };
      })
      .sort((a, b) => b.generatedRevenue - a.generatedRevenue);
  });

  ngOnInit(): void {
    this.reload();
  }

  reload(): void {
    this.revenueStore.loadRevenues();
    if (this.bundleStore.bundles().length === 0) {
      this.bundleStore.loadBundles();
    }
  }

  formatCurrency(value: number): string {
    try {
      return new Intl.NumberFormat('ro-RO', {
        style: 'currency',
        currency: 'RON',
      }).format(value);
    } catch {
      return `${value.toFixed(2)} RON`;
    }
  }
}
